### ISSUE TITLE
AppModule 내의 변수 접근 범위 변경 외 몇 가지

### ISSUE THREAD

**Issue by bigstark** [omjoonkim/Mission#1]
https://github.com/omjoonkim/GitHubBrowserApp/blob/126ed77384191e9bde8d08d4297bf4743e4325c4/app/src/main/java/com/omjoonkim/app/mission/di/AppModule.kt#L19-L56

# AppModule.kt 내의 변수 접근 범위 변경 
`gson` / `apiClient` / `gitHubDataRepository` 변수 모두 `environment` 라는 변수를 통해 제공이 되고 있습니다.
위의 변수들을 private 으로 두지 않는다면 environment 로서 따로 제공하는 의미가 없을 듯 합니다.

# apiClient 변수 제거
`gitHubDataRepository` 는 `apiClient` 를 Wrapping 하여 기능을 하고있습니다. 
즉 environment 변수에서 apiClient 를 따로 제공할 필요가 없습니다.
실제로 environment 변수에서 apiClient 를 받아서 사용하는 경우가 존재하지 않습니다.

# 변수 오타 수정

enviroment -> environment

**Comment by omjoonkim** [comment]
👍
AppComponent를 활용한 DI는 어떻게 생각하시나요?

**Comment by bigstark** [comment]
그부분은 새로운 이슈로 관리하는 편이 좋을 것 같습니다!

**Comment by omjoonkim** [comment]
해결~
