### ISSUE TITLE
APIService 내의 Endpoint object

### ISSUE THREAD

**Issue by bigstark** [omjoonkim/Mission#2]
https://github.com/omjoonkim/GitHubBrowserApp/blob/126ed77384191e9bde8d08d4297bf4743e4325c4/app/src/main/java/com/omjoonkim/app/mission/network/APIService.kt#L9-L20

# Endpoint object 제거
`Endpoint` 라는 object name 에 `baseUrl` 밖에 존재하지 않습니다. 
endpoint 변수를 추가한다면 필요한 object 가 되겠으나 현재 그렇게 사용하고 있지 않으니 제거하는 것이 어떨까요?

# baseUrl 위치 변경
`baseUrl` 자체를 `build.gradle` 내의 `buildConfigField` 변수로 정의해놓는 것이 어떨까요?

**Comment by omjoonkim** [comment]
코드 수정 되었습니당. :)
